controller_manager:
  ros__parameters:
    update_rate: 30
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ['base_link_left_wheel_joint']
    right_wheel_names: ['base_link_right_wheel_joint']
    wheel_separation: 0.38
    wheel_radius: 0.025

head_controller:
  ros__parameters:
    joints:
      - head_base_neck_pan_link
      - head_base_tilt_pan_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
